version: '3.8'

services:
  api-gateway:
    build:
      context: ../gateway-api
    ports:
      - "5000:5000"
    env_file:
      - ${ENV_FILE}  # Archivo de entorno especificado al ejecutar
    depends_on:
      - auth-service
      - qa-service
    restart: always
    networks:
      - my-network

  auth-service:
    build:
      context: ../auth-service
    ports:
      - "5001:5001"
    env_file:
      - ${ENV_FILE}  # Archivo de entorno especificado al ejecutar
    volumes:
      - ../auth-service/instance:/app/instance 
    restart: always
    networks:
      - my-network

  postgres:
    image: postgres:15
    container_name: postgres_container
    # environment:
    #   POSTGRES_USER: ${POSTGRES_USER}
    #   POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    #   POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    env_file:
      - ${ENV_FILE}  # Archivo de entorno especificado al ejecutar
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    networks:
      - my-network

  qa-service:
    build:
      context: ../qa-service
    ports:
      - "5003:5003"
    env_file:
      - ${ENV_FILE}  # Archivo de entorno especificado al ejecutar
    depends_on:
      - postgres
    volumes:
      - ../qa-service:/app
    restart: always
    networks:
      - my-network

volumes:
  postgres_data:
    external: false

networks:
  my-network:
    driver: bridge
