version: '3.8'

services:
 

  auth-service:
    build:
      context: ../auth-service
    ports:
      - "5001:5001"
    env_file:
      - ${ENV_FILE}  # Archivo de entorno especificado al ejecutar
    depends_on:
      - postgres-auth
    volumes:
      - ../auth-service:/app
    restart: always
    networks:
      - my-network

    
  postgres-auth:
    image: postgres:15
    container_name: postgres-auth
    ports:
      - "5434:5432"
    env_file:
      - ${ENV_FILE}
    volumes:
      - postgres_auth_data:/var/lib/postgresql/data
    restart: always
    networks:
      - my-network

volumes:
  postgres_auth_data:
    external: false

networks:
  my-network:
    driver: bridge
