version: '3.8'

services:
  api-gateway:
    build:
      context: ../gateway-api
    ports:
      - "5000:5000"
    # profiles: 
    #   - nolevantar  
    env_file:
      - ${ENV_FILE}  # Archivo de entorno especificado al ejecutar
    depends_on:
      - auth-service
      # - qa-service
    restart: always
    networks:
      - my-network

  auth-service:
    build:
      context: ../auth-service
    ports:
      - "5001:5001"
    env_file:
      - ${ENV_FILE}  # Archivo de entorno especificado al ejecutar
    volumes:
      - ../auth-service/instance:/app/instance 
    restart: always
    networks:
      - my-network

  postgres-qa:
    image: postgres:15
    container_name: postgres_qa
    ports:
      - "5432:5432"
    env_file:
      - ${ENV_FILE}
    environment:
      POSTGRES_DB: ${POSTGRES_DB_QA}  # Base de datos para QA
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_qa_data:/var/lib/postgresql/data
    restart: always
    networks:
      - my-network

  postgres-competition:
    image: postgres:15
    container_name: postgres_competition
    ports:
      - "5433:5432"  # Cambia el puerto para evitar conflictos
    env_file:
      - ${ENV_FILE}
    environment:
      POSTGRES_DB: ${POSTGRES_DB_COMPETITION}  # Base de datos para Competition
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_competition_data:/var/lib/postgresql/data
    restart: always
    networks:
      - my-network

  qa-service:
    build:
      context: ../qa-service
    # profiles: 
    #   - nolevantar
    ports:
      - "5003:5003"
    env_file:
      - ${ENV_FILE}  # Archivo de entorno especificado al ejecutar
    depends_on:
      - postgres
    volumes:
      - ../qa-service:/app
    restart: always
    networks:
      - my-network

volumes:
  postgres_qa_data:
    external: false
  postgres_competition_data:
    external: false
    
networks:
  my-network:
    driver: bridge
