version: '3.8'
services:
  api-gateway:
    build:
      context: ../gateway-api
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - auth-service
    environment:
      FLASK_ENV: ${FLASK_ENV}
    networks:
      - my-network  # Especificamos la red

  auth-service:
    build:
      context: ../auth-service
    ports:
      - "5001:5001"
    env_file:
      - .env
    volumes:
      - ../auth-service/instance:/app/instance 
    networks:
      - my-network  # Especificamos la misma red

networks:
  my-network:   # Definimos la red
    driver: bridge
