name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Clonar el repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # Configurar Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Instalar Docker Compose
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      # Iniciar servicios y probar la construcción
      - name: Build and run services
        run: |
          docker-compose up --build -d
          sleep 10 # Esperar a que los servicios inicien
          docker-compose ps

      # Verificar conectividad entre servicios
      - name: Test API Gateway
        run: |
          curl -f http://localhost:5000/ || exit 1

      - name: Test Auth Service
        run: |
          curl -f http://localhost:5001/ || exit 1

      # Detener y limpiar
      - name: Clean up
        run: docker-compose down
